module.exports=[
    {type:'WORDS', name:'差错', desc:'差(chā)错。'},
    {type:'WORDS', name:'差池', desc:'差(cha1)池：差错、意外的意思，相比差迟更常用。'},
    {type:'WORDS', name:'差迟', desc:'差(cha4)迟：意同差池，但比较少用。'},
    {type:'WORDS', name:'冠冕', desc:'冠(gua1n)冕：古代皇冠或官员的帽子。'},
    {type:'WORDS', name:'裨益', desc:'裨(bi4)益：益处，补益。'},
    {type:'WORDS', name:'裨将', desc:'裨(pi2)将：副将。'},
    {type:'WORDS', name:'剽悍', desc:'剽(pia1o)悍：灵活而勇敢。'},
    {type:'WORDS', name:'慓悍', desc:'慓(pia1o)悍：轻捷勇猛。'},
    {type:'WORDS', name:'骠勇', desc:'骠(pia4o)勇：⑴形容马快跑，⑵勇猛。'},
    {type:'WORDS', name:'谐谑', desc:'谐(xie2)谑(xue4)：诙谐逗趣。'},
    {type:'WORDS', name:'禀赋', desc:'禀(bi3ng)赋：人所具有的智力、体魄等素质;天赋。'},
    {type:'WORDS', name:'胁从', desc:'胁(xie2)从：被迫相从者;胁迫别人相从。'},
    {type:'WORDS', name:'熟稔', desc:'熟(shu2)稔：指十分熟悉的意思。'},
    {type:'WORDS', name:'联袂', desc:'联袂(me4i)：联手;联合;携手并肩。'},
    {type:'WORDS', name:'鸟瞰', desc:'鸟瞰(ka4n)：从高处往下看，近义词为俯瞰、俯视，反义词是仰望、仰视。'},
    {type:'WORDS', name:'分蘖', desc:'分蘖(nie4)：禾本科等植物在地下或近地面处所生的分枝。'},
    {type:'WORDS', name:'封诰', desc:'封诰(ga4o)：明 清 帝王对五品以上官员及其先代和妻室授予封典的诰命。'},
    {type:'WORDS', name:'皓齿', desc:'皓(ha4o)齿：洁白的牙齿。'},
    {type:'WORDS', name:'蓑衣', desc:'蓑(suo1)衣：用棕榈皮编成的雨衣。'},
    {type:'WORDS', name:'针砭', desc:'针砭(bia1n)：⑴古代的一种针刺疗法，现已失传。砭是古代治病的石头针。⑵比喻指出错误，劝人改正。'},
    {type:'WORDS', name:'舶来品', desc:'舶(bo2)来品：指通过航船从国外进口来的物品。'},
    {type:'WORDS', name:'沉湎', desc:'沉湎：沉溺，耽于。比喻潜心于某事物或处于某种境界或思维活动中。'},
    {type:'WORDS', name:'寒暄', desc:'寒暄：问寒问暖。今多泛指宾主见面时谈天气冷暖之类的应酬话(暄:温暖)。'},
    {type:'WORDS', name:'蛰伏', desc:'蛰(zhe2)伏：蛰本义指动物冬眠，藏起来不吃不动。也比喻人或者事物、事件隐藏不露面，比如蛰伏乡间。现代科学研究表明，蛰伏是一种介于睡觉和完全冬眠之间的状态，在此期间，动物的身体温度明显下降。'},
    {type:'WORDS', name:'编纂', desc:'编纂(zua3n)：编辑，撰述编纂词典十年，始有事略之编纂。--孙文《黄化冈七十二烈士事略·序》。'},
    {type:'WORDS', name:'昭示', desc:'昭示：明白地表示或宣布。'},
    {type:'WORDS', name:'缄默', desc:'缄(jia1n)默：闭口不说话。缄默也是一种症状，指言语器官无器质性病变，智力发育也无障碍而表现沉默不语。'},
    {type:'WORDS', name:'渐染', desc:'渐(jia1n)染：因接触久了而逐渐受到影响。'},
    {type:'WORDS', name:'殷红', desc:'殷(ya1n)红：发黑的红色。'},
    {type:'WORDS', name:'荫庇', desc:'荫(yi4)庇：大树遮住炙人的阳光，旧时比喻尊长照顾着晚辈或祖宗保佑着子孙。'},
    {type:'WORDS', name:'伛偻', desc:'伛(yv3)偻(lv3)：腰背弯曲。'},
    {type:'WORDS', name:'囹圄', desc:'囹(li2ng)圄(yv3)：监狱。'},
    {type:'WORDS', name:'瘐毙', desc:'瘐(yv3)毙：关在牢狱里的人因受刑或饥寒、疾病而死亡。也作“瘐死”。'},
    {type:'WORDS', name:'箴言', desc:'箴(zhe1n)言：规劝的话。'},
    {type:'WORDS', name:'诟詈', desc:'诟(go4u)詈(li4)：辱骂，责骂。'},
    {type:'WORDS', name:'舷梯', desc:'舷(xia2n)梯：平时收藏于船舷（飞机）内，用时放出舷外沿舷边倾斜布置，供人员上下船用的梯。'},
    {type:'WORDS', name:'按捺', desc:'按捺(na4)：抑制；忍耐。'},
    {type:'WORDS', name:'笑靥', desc:'笑靥(ye4)：微笑时颊部露出来的酒窝儿。如：她面带笑靥。后“笑靥”泛指美女的笑脸。有词“笑靥如花”。'},
    {type:'WORDS', name:'绵亘', desc:'绵亘(ge4n)：绵延不断。例：大别山~在河南、安徽和湖北三省的边界上。'},
    {type:'WORDS', name:'荆杞', desc:'荆杞：1、指荆棘和枸杞，皆野生灌木，带钩刺，每视为恶木。因亦用以形容蓁莽荒秽、残破萧条的景象。2、喻奸臣。'},
    {type:'WORDS', name:'伉俪', desc:'伉俪：对别的夫妻的称呼。把对方及其配偶尊称为“贤伉俪”。'},
    {type:'WORDS', name:'羞赧', desc:'羞赧(na3n)：因害羞而脸红的样子。'},
    {type:'WORDS', name:'木讷', desc:'木讷(ne4)：指反应迟钝，呆头呆脑，话语不多。通常都是用来比喻人，木讷的人，呆板的人。也可以形容人的性格。'},
    {type:'WORDS', name:'怃然', desc:'怃(wu3)然：1.怅然失意貌。2.惊愕貌。'},
    {type:'WORDS', name:'粗犷', desc:'粗犷(gua3ng)：粗鲁强横，粗率豪放，如自然生长般未经修饰。'},
    {type:'WORDS', name:'粳米', desc:'粳(ji1ng)米：粳米是用粳型非糯性稻谷碾制成的米。'},
    {type:'WORDS', name:'窜改', desc:'窜(cua4n)改：改动;删改。'},
    {type:'WORDS', name:'连累', desc:'连累(le3i)：由于个人或小集体的原故而使别人也牵连受害。'},
    {type:'WORDS', name:'氤氲', desc:'氤(yi1n)氲(yu1n)：也作“烟煴”“絪缊”，指湿热飘荡的云气，烟云弥漫的样子。也有“充满"的意思。'},
    {type:'WORDS', name:'慢腾腾', desc:'慢腾腾：形容缓慢。'},
    {type:'WORDS', name:'颤栗', desc:'颤(zha4n)栗：颤抖哆嗦，也作“战栗”。'},
    {type:'WORDS', name:'积攒', desc:'积攒(za3n)：一点一点地聚集。'},
    {type:'WORDS', name:'铡刀', desc:'铡(zha2)刀：可对折的切草的刀。'},
    {type:'WORDS', name:'饿殍', desc:'饿殍(pia3o)：指饿死的人。常用词语有饿殍遍野。'},
    {type:'WORDS', name:'缥缈', desc:'缥缈：亦作“飘渺”。汉语词汇。隐隐约约，若有若无的样子。形容空虚渺茫。一般指心中想要而现实中不可得到的东西，并非指虚无，不存在于现实的东西。也可形容富有美感。'},
    {type:'WORDS', name:'醅酒', desc:'醅(pe1i)酒：未滤去糟的酒。'},
    {type:'WORDS', name:'印绶', desc:'印绶(sho4u)：1、印信和系印信的丝带。古人印信上系有丝带，佩带在身。2、借指官爵。'},
    {type:'WORDS', name:'疏浚', desc:'疏浚：疏通淤塞的河道、港口。'},
    {type:'WORDS', name:'涣散', desc:'涣散：[精神、组织、纪律等] 散漫;松懈。'},
    {type:'WORDS', name:'推诿', desc:'推诿(we3i)：推卸责任、推辞，即缺乏责任心，对事具有消极表现。'},
    {type:'WORDS', name:'倾轧', desc:'倾轧(ya4)：以争吵、摩擦和对立为特色的持久的不和。'},
    {type:'WORDS', name:'蓬蒿', desc:'蓬蒿(ha1o)：茼蒿 （tónghāo）的别名。'},
    {type:'WORDS', name:'只恁', desc:'只(zhi1)恁(ne4n)：就这样；只是这样。'},
    {type:'WORDS', name:'盥洗', desc:'盥(gua4n)洗：指洗手或洗脸，以手承水冲洗而下流于盘（皿）。盥,澡手也。从臼水临皿。'},
    {type:'WORDS', name:'埋怨', desc:'埋(ma2n)怨：因为事情不如意而不满或怨恨。'},
    {type:'WORDS', name:'霄汉', desc:'霄汉：云霄和天河，指天空，比喻朝庭。'},
    {type:'WORDS', name:'哂笑', desc:'哂(she3n)笑：1.讥笑，有嘲讽的意思 2.强颜欢笑。'},
    {type:'WORDS', name:'矍铄', desc:'矍(jue2)铄(shuo4)：形容老人目光炯炯、精神健旺。'},
    {type:'WORDS', name:'倥偬', desc:'倥(ko3ng)偬(zo3ng)：① 忙乱、事情的纷繁迫促，匆忙。戎马倥偬。②困苦窘迫。'},
    {type:'WORDS', name:'祛除', desc:'祛(qu1)除：驱散;消除。'},
    {type:'WORDS', name:'澎湃', desc:'澎湃(pa4i)：1.形容波浪猛烈的发出巨大声响的撞击；2.指声势、气势等浩大雄伟。'},
    {type:'WORDS', name:'掣肘', desc:'掣(che4)肘(zho3u)：原意指拉着胳膊，比喻有人从旁牵制，工作受干扰。例如：暗中掣肘；由于受到掣肘，工作难以开展。'},
    {type:'WORDS', name:'自刭', desc:'自刭(ji3ng)：用刀割脖子。'},
    {type:'WORDS', name:'诡谲', desc:'诡谲(jue2)：1.奇异多变；2.离奇古怪。'},
    {type:'WORDS', name:'脖颈', desc:'脖颈(ge3ng)：口语指脖子。亦称“脖颈儿”，是人体头部以下，肩以上的部位。'},
    {type:'WORDS', name:'谄媚', desc:'谄(cha3n)媚：卑微地奉承，讨好别人。'},
    {type:'WORDS', name:'啁啾', desc:'啁(zho1u)啾(qiu1)：形容鸟叫声、奏乐声等。'},
    {type:'WORDS', name:'赠遗', desc:'赠遗(we4i)：赠送，赠给。亦指赠送的财物。'},
    {type:'WORDS', name:'平添', desc:'平添：平白或自然而然地增添。'},
    {type:'WORDS', name:'投奔', desc:'投奔(be4n)：指前往依靠别人或落脚依靠的人或地方。'},
    {type:'WORDS', name:'悄然', desc:'悄(qia3o)然：1、忧伤貌。2、形容安静而无声，寂静地。3.浑然，依然。'},
    {type:'WORDS', name:'泥淖', desc:'泥淖(na4o)：指泥泞的低洼地，也指烂泥、泥坑。淖是烂泥的意思。比喻艰难而不易摆脱的困境。'},
    {type:'WORDS', name:'煊赫', desc:'煊(xua1n)赫：形容名声大、声势盛。', example:''},
    {type:'WORDS', name:'悭吝', desc:'悭(qia1n)吝：亦作“悭悋”“悭恡（lìn）”，吝啬；小气。', example:''},
    {type:'WORDS', name:'涟猗', desc:'涟猗(yi1)：亦作“涟漪”。被风吹起的水面的波纹。在平静水面上,微风吹来激起的细浪。', example:''},
    {type:'WORDS', name:'睥睨', desc:'睥(pi4)睨(ni4)：斜着眼看，侧目而视，有厌恶或高傲之意。', example:''},
    {type:'WORDS', name:'消弭', desc:'消弭：亦作“消弥”。意思为清除、消除某些不好的事情。', example:''},
    {type:'WORDS', name:'妥帖', desc:'妥帖：亦作“妥怗”、“妥贴”。恰当，十分合适。', example:''},
    {type:'WORDS', name:'伶俜', desc:'伶(li2ng)俜(pi1ng)：1、指孤单，孤独。2. 孤立。3. 飘泊；流离。4. 引申指残落，凋零。5. 艰难。', example:''},
    {type:'WORDS', name:'关隘', desc:'关隘(a4i)：又称关卡。险要的关口。在交通要道设立的防务设施。', example:''},
    {type:'WORDS', name:'搓捻', desc:'搓捻(nia3n)：将线、纸等放在手里来回搓。将某种揉捏成条状物。', example:''},
    {type:'WORDS', name:'毗邻', desc:'毗(pi2)邻：指边界接壤的意思，毗邻多指陆地相接。', example:''},
    {type:'WORDS', name:'跻身', desc:'跻(ji1)身：置身[某种行列、境域等];踏进。突然获得成绩。', example:''},
    {type:'WORDS', name:'怄气', desc:'怄(o4u)气：生闷气，心怀不满。', example:''},
    {type:'WORDS', name:'熨帖', desc:'熨(yu4)帖：1.指用字、词等妥当、合适；2.心中没有波澜，平静；3.〈方〉妥当；4.〈方〉舒服。', example:''},
    {type:'WORDS', name:'岑寂', desc:'岑(ce2n)寂：1.高而静。亦泛指寂静。2.寂寞，孤独冷清，山堂夜岑寂。', example:''},
    {type:'WORDS', name:'谙习', desc:'谙(a1n)习：熟习。', example:''},
    {type:'WORDS', name:'惭怍', desc:'惭怍(zuo4)：惭愧、羞惭不安。', example:''},
    {type:'WORDS', name:'呓语', desc:'呓(yi4)语：(1) 梦话；(2) 比喻荒谬糊涂的话。', example:''},
    {type:'WORDS', name:'箍桶', desc:'箍(gu1)桶：用箍将做桶的板捆在一起，迫使其成为所需形状和确保接缝严实。', example:''},
    {type:'WORDS', name:'轱辘', desc:'轱(gu1)辘(lu)：用不同材料制成的圆形滚动物体。简单来说，它包括轮子的外圈、与外圈相连接的辐条和中心轴。透过滚动，轮子可以大大的减少与接触面的磨擦系数。如果配上轴，即成为车的最主要构成部份。轮子在交通运输中非常有用，是人类的重要发明之一。除了车轮以外，其他圆形的轮还有船轮、飞轮等等。', example:''},
    {type:'WORDS', name:'翩跹', desc:'翩跹(xia1n)：亦作“蹁跹”。形容轻快地跳舞。', example:''},
    {type:'WORDS', name:'采撷', desc:'采撷(xie2)：指摘取；犹采摘。', example:''},
    {type:'WORDS', name:'绯红', desc:'绯(fe1i)红：绯红，中国传统色彩名称，红色的一种，艳丽的深红、鲜红、通红、深红色 。绯红色英文之语源是从梵语krmi-ja得来，“由虫生产的红色染料”的意思。', example:''},
    {type:'WORDS', name:'发轫', desc:'发(fa1)轫(re4n)：1.拿掉支住车轮的木头，使车前进。借指出发，起程。2.动用，动员。3.比喻新事物或某种局面开始出现：发轫之作。4.犹发迹。', example:''},
    {type:'WORDS', name:'禅让', desc:'禅(sha4n)让：统治者把首领之位让给别人。尧是黄帝以后比较著名部落联盟首领，尧去世后，尧把部落联盟首领位置让于舜，推舜为帝。这种让位，历史上称为“禅让”。唐尧传位给虞舜，同时传了允执厥中四个字；虞舜传位给大禹，同时传了尧舜十六字心传（简称中华心法），成为五千年治国的国家哲学。', example:''},
    {type:'WORDS', name:'悲怆', desc:'悲怆(chua4ng)：悲伤。', example:''},
    {type:'WORDS', name:'寒碜', desc:'寒碜(che3n)：亦作“寒伧(chen)”。寒酸，穷酸难看、不体面；丢脸；讥笑，揭人短处，使之丢脸。', example:''},
    {type:'WORDS', name:'创伤', desc:'创(chua1ng)伤：1.受伤的地方。比喻遭受的伤害或破坏。2.能引起持久病变的身体损伤，或能引起异常情绪的精神上或感情上的打击。', example:''},
    {type:'WORDS', name:'讥诮', desc:'讥诮(qia4o)：风言冷语地讥嘲。', example:''},
    {type:'WORDS', name:'撂手', desc:'撂(lia4o)手：作罢;丢开不管。不继续做下去；丢开。', example:'1.～不管。2.事情没有完，哪能就～？'},
    {type:'WORDS', name:'纰漏', desc:'纰(pi1)漏：因疏忽而产生的错误疏漏。', example:''},
    {type:'WORDS', name:'罡风', desc:'罡(ga1ng)风：道家称天空极高处的风，现在有时用来指强烈的风，所到之处，扫荡一切。', example:''},
    {type:'WORDS', name:'锃亮', desc:'锃(ze4ng)亮：反光发亮，闪光耀眼。', example:''},
    {type:'WORDS', name:'拮据', desc:'拮据(ju1)：1.原指鸟衔草筑巢，鸟足(手)劳累。2.后比喻经济窘迫。', example:''},
    {type:'WORDS', name:'模样', desc:'模(mu2)样：1.人的长相或装束打扮的样子。2.表示约略。', example:''},
    {type:'WORDS', name:'补缀', desc:'补缀(zhui4)：指缝补连缀；泛指修补。', example:''},
    {type:'WORDS', name:'贸然', desc:'贸然：轻率的样子。指遇事不经深思熟虑，随便就决定做法。《现代汉语词典》里面只收录了“贸然”一词，没有收录“冒然”。冒然与贸然两词在现在的许多口语和网络上已经混淆通用，“贸然”是规范写法，在学生考试答卷上，“冒然”是错的。', example:''},
    {type:'WORDS', name:'啮噬', desc:'啮(nie4)噬：咬嚼，咬食。', example:''},
    {type:'WORDS', name:'倨傲', desc:'倨(ju4)傲：形容（人）高傲自大、傲慢的样子。', example:''},
    {type:'WORDS', name:'碾盘', desc:'碾(nia3n)盘：用来承托碾磙子碾去谷壳的石底盘。', example:''},
    {type:'WORDS', name:'沏茶', desc:'沏(qi1)茶：沏：用开水冲。', example:''},
    {type:'WORDS', name:'孩提', desc:'孩提：2～3岁的儿童。幼儿时期。', example:''},
    {type:'WORDS', name:'佣金', desc:'佣(yo4ng)金：旧时作买卖付给中间人的报酬。', example:''},
    {type:'WORDS', name:'怯懦', desc:'怯(qie4)懦：胆小懦弱。', example:''},
    {type:'WORDS', name:'攒射', desc:'攒(cua2n)射：密集地集中射击。', example:''},
    {type:'WORDS', name:'赈灾', desc:'赈(zhe4n)灾：赈济灾荒救助灾害救济灾民。', example:''},
    {type:'WORDS', name:'肯綮', desc:'肯綮(qi4ng)：筋骨结合的地方，比喻要害或最重要的关键。', example:''},
    {type:'WORDS', name:'偌大', desc:'偌(ruo4)大：指这么大，如此之大。', example:''},
    {type:'WORDS', name:'搦管', desc:'搦(nuo4)管：1.握笔；执笔为文。2.谓吹奏管乐器。', example:''},
    {type:'WORDS', name:'黧黑', desc:'黧(li2)黑：形容人的脸色黑。', example:'面目～'},
    {type:'WORDS', name:'央浼', desc:'央浼(me3i)：亦作“央凂”。指不断地请求，恳求。', example:''},
    {type:'WORDS', name:'蚊蚋', desc:'蚊蚋(rui4)：通常指蚊子。1.食人血的蚊子叫蚋，食植物汁液的蚊子叫蚊。2.比喻坏人。', example:''},
    {type:'WORDS', name:'喋血', desc:'喋(die2)血(xue4)：形容血流遍地，指杀人很多。也作蹀血。', example:''},
    {type:'WORDS', name:'轧钢', desc:'轧(zha2)钢：在旋转的轧辊间改变钢锭，钢坯形状的压力加工过程叫轧钢。轧钢的目的与其他压力加工一样，一方面是为了得到需要的形状，例如：钢板，带钢，线材以及各种型钢等；另一方面是为了改善钢的内部质量，我们常见的汽车板、桥梁钢、锅炉钢、管线钢、螺纹钢、钢筋、电工硅钢、镀锌板、镀锡板，包括火车轮都是通过轧钢工艺加工出来的。', example:''},
    {type:'WORDS', name:'胳臂', desc:'胳臂(bei)：指肩以下手腕以上的部位，即胳膊(bo)。', example:''},
    {type:'WORDS', name:'撺掇', desc:'撺(cua1n)掇(duo)：1、在一旁鼓动人做某事。 2、催逼；催促；煽动；怂恿。 3、张罗，安排。 4、帮助。 5、古典戏曲乐器演奏术语。', example:''},
    {type:'WORDS', name:'档次', desc:'档(da4ng)次：指事或物好坏的等级、层次。', example:'新生代的衣着～就是比老一辈高。'},
    {type:'WORDS', name:'和煦', desc:'和煦(xu4)：形容温暖的阳光。', example:''},
    {type:'WORDS', name:'拓本', desc:'拓(ta4)本：凡摹拓金石、碑碣、印章之本，皆称为“拓本”，即用纸紧覆在碑碣或金石等器物的文字或花纹上，用墨或其他颜色打出其文字、图形来的印刷品。', example:''},
    {type:'WORDS', name:'蹩脚', desc:'蹩(bie3)脚：指质量差、技艺差。有质量低劣的；不老练的或不圆滑的； 失意潦倒三方面意思。', example:'他早忘了～时候过的是什么日子。'},
    {type:'WORDS', name:'誊写', desc:'誊(te2ng)写：指照着抄写。', example:''},
    {type:'WORDS', name:'拜谒', desc:'拜谒(ye4)：1.拜访谒见。2.参拜瞻仰(陵墓、碑碣等处)。', example:'这几天你们已经看见有几万几十万劳动者来～列宁同志的灵柩。'},
    {type:'WORDS', name:'纠葛', desc:'纠葛(ge2)：1.紧紧深陷、纠缠或卷入似乎难以挣脱的困难。2.纠缠不清的事情;纠纷。', example:''},
    {type:'WORDS', name:'挨宰', desc:'挨宰：比喻购物或接受服务时被索取高价而遭受经济损失。', example:''},
    {type:'WORDS', name:'谥号', desc:'谥(shi4)号：分为官谥和私谥两大类。古代东亚（包括中国、朝鲜、越南、日本）帝王及其后妃、诸侯、臣僚等具有一定地位的人死后，内务府根据其生前事迹与品德，而给予他一个中肯的称号。此外，受中华文化影响的一些邻近国家亦有使用，但不是每个东亚古代国家都用谥号。根据对西周青铜铭文的研究，约周穆王时期，给地位较高或较有身份的死者加谥的做法已比较普遍。', example:''},
    {type:'WORDS', name:'巨擘', desc:'巨擘(bo4)：1.大拇指。2.比喻杰出人物;在某一方面居于首位的人物。', example:''},
    {type:'WORDS', name:'羁縻', desc:'羁縻(mi2)：1.笼络。2.束缚，控制。3.拘禁。', example:''},
    {type:'WORDS', name:'沉疴', desc:'沉疴(ke1)：久治不愈的病。', example:''},
    {type:'WORDS', name:'入殓', desc:'入殓(lia4n)：又叫“入棺”、“入木”、“落材”，古称“大殓”，指将尸体移入棺木。各地时间不一，有3天、5天或7天入殓。', example:''},
    {type:'WORDS', name:'荼蘼', desc:'荼(tu2)蘼(mi2)：为落叶灌木，以地下茎繁殖。荼蘼花在春季末夏季初开花，凋谢后即表示花季结束，所以有完结的意思。', example:''},
    {type:'WORDS', name:'信笺', desc:'信笺(jia1n)：信纸的古代说法。', example:''},
    {type:'WORDS', name:'妩媚', desc:'妩(wu3)媚：一般用来形容女子姿容美好、可爱，柔媚的风格。一般极少用在年幼女性身上。', example:''},
    {type:'WORDS', name:'牴牾', desc:'牴(di3)牾(wu3)：同“抵啎”、“抵牾”。抵触，矛盾。', example:''},
    {type:'WORDS', name:'朝暾', desc:'朝(zha1o)暾(tu1n)：形容初升的太阳，阳光明亮温暖，亦指早晨的阳光。', example:''},
    {type:'WORDS', name:'稍息', desc:'稍(sha4o)息：军事或体操口令，命令队伍或个人从立正姿势变为休息姿势。', example:''},
    {type:'WORDS', name:'靓妆', desc:'靓(ji4ng)妆：1.浓妆艳抹。2.借指妆饰华美的女子。3.打扮。4.指打扮得很美丽，浓妆艳抹。“靓妆”要和“靓装”区别开来。', example:''},
    {type:'WORDS', name:'行藏', desc:'行藏：指出处或行止。常用以说明人物行止、踪迹和底细等。', example:''},
    {type:'WORDS', name:'行款', desc:'行(ha2ng)款：1.文字的书写顺序和排列形式，包括字序和行序。2.比喻某种标准或规格。', example:''},
    {type:'WORDS', name:'道行', desc:'道行(he2ng)：1.僧道修行的功夫。2.比喻技能本领。', example:''},
    {type:'WORDS', name:'舌苔', desc:'舌苔(ta1i)：中医术语。正常人的舌背上有一层薄白而润的苔状物，叫舌苔。由脱落的角化上皮、唾液、细菌、食物碎屑及渗出的白血细胞等组成。在正常情况下，由于咀嚼和吞咽动作，以及唾液、饮食的冲洗，经常不断地清除掉舌表面的物质，仅表现为薄白的一层舌苔。当患病时，进食少或只进软食，使咀嚼和舌的动作减少，或唾液分泌减少，舌苔就变厚。正常人的舌苔，一般是薄而均匀地平铺在舌面，在舌面中部、根部稍厚。', example:''},
    {type:'WORDS', name:'辘轳', desc:'辘(lu4)轳(lu)：1.安在井上绞起汲水斗的器具。2.机械上的绞盘。', example:''},
    {type:'WORDS', name:'鳜鱼', desc:'鳜(gui4)鱼：又名鳜花鱼、桂花鱼、花鲫鱼等。是一种家常的可以食用的鱼类。', example:''},
    {type:'WORDS', name:'菡萏', desc:'菡(ha4n)萏(da4n)：古人称未开的荷花为菡萏，即花苞。', example:''},
    {type:'WORDS', name:'掉色', desc:'掉色(sha3i)：褪色，颜色变淡和不全。比喻某种情景等逐渐淡漠以至消失。', example:''},
    {type:'WORDS', name:'豁出去', desc:'豁(huo1)出去：豁：摒弃；舍却。如豁出性命。', example:''},
    {type:'WORDS', name:'愆伏', desc:'愆(qia1n)伏：谓阴阳失调。多指气候失常。', example:'～之灾'},
    {type:'WORDS', name:'沙碛', desc:'沙碛(qi4)：指沙滩、沙洲，也可指沙漠。', example:''},
    {type:'WORDS', name:'姣好', desc:'姣(jia1o)好：形容容貌美丽。', example:''},
    {type:'WORDS', name:'应验', desc:'应(yi4ng)验：后来发生的事实与预先所言，所估计的相符。', example:'他的话～了。'},
    {type:'WORDS', name:'口供', desc:'口供(go4ng)：受审者口头陈述的供词。', example:''},
    {type:'WORDS', name:'蓓蕾', desc:'蓓蕾(le3i)：也作“蓓藟”。花蕾，含苞未放的花儿。', example:''},
    {type:'WORDS', name:'漱口', desc:'漱(shu4)口：用一种液体漱口腔及喉咙的行为。', example:''},
    {type:'WORDS', name:'感喟', desc:'感喟(kui4)：感慨;叹息。', example:''},
    {type:'WORDS', name:'鞭鞘', desc:'鞭鞘(sha1o)：鞭子末端的软性细长物，常以皮条或丝为之。亦借指鞭子。', example:''},
    {type:'WORDS', name:'讪笑', desc:'讪(sha4n)笑：羞惭而尴尬地笑。亦指讥笑或厚颜强笑，勉强装笑', example:''},
    {type:'WORDS', name:'谰言', desc:'谰(la2n)言：指诬妄不实、无根据的话。', example:''},
    {type:'WORDS', name:'落价', desc:'落(la4o)价：价格下跌、下降。', example:''},
    {type:'WORDS', name:'棺椁', desc:'棺椁(guo3)：棺材和套棺（古代套于棺外的大棺），泛指棺材。红色棺椁亦作“ 棺郭 ”。 指的是装殓尸体的器具，椁，套在棺外的外棺，就是棺材外面套的大棺材。', example:''},
    {type:'WORDS', name:'强迫', desc:'强(qia3ng)迫：施加压力使服从；迫使。是建立在自己意志的情况下来迫使别人服从。', example:''},
    {type:'WORDS', name:'氐惆', desc:'氐(di1)惆：昏乱不安；郁闷不舒畅。', example:''},
    {type:'WORDS', name:'歆慕', desc:'歆(xi1n)慕：羡慕。', example:''},
    {type:'WORDS', name:'远岫', desc:'远岫(xiu4)：远处的峰峦。', example:''},
    {type:'WORDS', name:'涅槃', desc:'涅(nie4)槃：[佛教]正觉的境界，在此境界，贪、嗔、痴与以经验为根据的我亦已灭尽，达到寂静、安稳和常在。调理自己的思想，断除大脑里面不好的思想、程序、情感，最终达到没有烦恼，超脱生死的境界，也就是无所得，无执着，随缘。', example:''},
    {type:'WORDS', name:'痔瘘', desc:'痔(zhi4)瘘(lo4u)：临床上常见病、多发病。痔瘘的主要症状有便血、疼痛、脱出、局部分泌物增多和排便困难等。发病的主要原因是由于人体阴阳失调，加之外感风、热、燥、湿之邪， 内伤六淫七情等因素所致。', example:''},
    {type:'WORDS', name:'招徕', desc:'招徕(la2i)：招揽，招引到自己面前来；有时比喻招揽客人。', example:''},
    {type:'WORDS', name:'朴刀', desc:'朴(po1)刀：大刀的一种，是一种木柄上安有长而宽的钢刀的兵器。使用时，两手握着刀柄，像使用大刀那样，利用刀刃和刀本身的重量，来劈杀敌人。', example:'杨志提了～，拿了藤条，自去赶那担子。'},
    {type:'WORDS', name:'朴硝', desc:'朴(po4)硝：质地不纯的硫酸晶体，由海水或盐湖水熬过沉淀而成，用来硝皮革，也可供药用。', example:''},
    {type:'WORDS', name:'褶皱', desc:'褶(zhe3)皱：岩石沉积或固结后因受力作用而在岩石内弯曲成的拱或槽。', example:''},
    {type:'WORDS', name:'亲戚', desc:'亲戚(qi)：亲戚是指和自己有血亲和姻亲的人。中国古代唐朝学者孔颖达对亲戚的注解为：亲指族内，戚言族外。', example:''},
    {type:'WORDS', name:'勖勉', desc:'勖(xu4)勉：亦作“勗勉”。勉励。', example:''},
    {type:'WORDS', name:'腈纶', desc:'腈(ji1ng)纶：中国所产的聚丙烯腈纤维的商品名，是一种合成纤维，用来纺毛线或制人造毛皮。', example:''},
    {type:'WORDS', name:'剿说', desc:'剿(cha1o)说：抄袭别人的言论为己说。', example:''},
    {type:'WORDS', name:'尽早', desc:'尽(ji3n)早：尽：力求达到最大限度。同样有尽快、尽量。', example:''},
    {type:'WORDS', name:'箭镞', desc:'箭镞(zu2)：箭镞又名箭簇即金属箭头，古时有青铜质，后改进为铁质。镞通簇为通假字。', example:''},
    {type:'WORDS', name:'颀长', desc:'颀(qi2)长：1、[身材] 细长;修长。2、（身量）高。', example:''},
    {type:'WORDS', name:'绯闻', desc:'绯(fe1i)闻：旧指桃色新闻，明星名人的负评较多，现在通常是指影视及娱乐界某明星自身与周边异性或同性之间的情色故事。一般来说绯闻发生时，绯闻的男女主角都会有新作品（如新歌发片），一般而言是利用绯闻来炒作。', example:''},
    {type:'WORDS', name:'楹联', desc:'楹(yi2ng)联：挂或贴于楹柱上的对联。泛指对联。', example:''},
    {type:'WORDS', name:'鸟喙', desc:'鸟喙(hui4)：鸟嘴。常用来形容尖凸的人嘴。', example:''},
    {type:'WORDS', name:'觳觫', desc:'觳(hu2)觫(su4)：恐惧得发抖,恐惧颤抖的样子。', example:'申大头～惶恐，只是跪在地下磕头。'},
    {type:'WORDS', name:'摈弃', desc:'摈(bi4n)弃：主要指抛弃，多用于人和具体事物。', example:''},
    {type:'WORDS', name:'瞢然', desc:'瞢(me2ng)然：懵懂；糊里糊涂的样子。', example:''},
    {type:'WORDS', name:'觇视', desc:'觇(cha1n)视：亦作“觇眎”。窥视，探看。', example:''},
    {type:'WORDS', name:'杂烩', desc:'杂烩(hui4)：1.各种菜合在一起烩成的菜。2.比喻各种事物的集萃。', example:''},
    {type:'WORDS', name:'框架', desc:'框(kua4ng)架：1.提供形状或强度的结构系统(如屋架)。2.比喻事物的组织、结构。', example:''},
    {type:'WORDS', name:'缮写', desc:'缮(sha4n)写：誊写;抄写。', example:''},
    {type:'WORDS', name:'秕谷', desc:'秕(bi3)谷：指子粒不饱满的稻谷或谷子。也叫“秕谷子”。可以作为填充物做成枕头。也可以用粉碎机打成秕谷糠喂养家禽。', example:''},
    {type:'WORDS', name:'痼疾', desc:'痼(gu4)疾：指经久难治愈的病。', example:''},
    {type:'WORDS', name:'牛虻', desc:'牛虻(me2ng)：咬或骚扰牲畜的任何一种虻。身体长椭圆形，有灰黑黄褐等色，胸部和腹部有花纹。', example:''},
    {type:'WORDS', name:'绾结', desc:'绾(wa3n)结(jie2)：指系结；打结。', example:''},
    {type:'WORDS', name:'猪倌', desc:'猪倌(gua1n)：以养猪为业的人；和养猪有关的人员。', example:''},
    {type:'WORDS', name:'绷脸', desc:'绷(be3ng)脸：[口]不愉快的表情，拉长脸。', example:''},
    {type:'WORDS', name:'蹭蹬', desc:'蹭(ce4ng)蹬(de4ng)：1.路途险阻难行。比喻困顿不顺利。2.倒霉;失势。', example:''},
    {type:'WORDS', name:'翁媪', desc:'翁媪(a3o)：老翁与老妇的并称。亦指年老的父母。', example:''},
    {type:'WORDS', name:'街坊', desc:'街坊(fang)：1、[block]∶街巷，也指城市中以道路或自然界线（如河流）划分的居住生活区。2、[neighbour] [口]∶同街巷的邻居。', example:''},
    {type:'WORDS', name:'角力', desc:'角(jue2)力：徒手相搏，较量武力。', example:''},
    {type:'WORDS', name:'杉篙', desc:'杉(sha1)篙(ga1o)：杉树一类的树干砍去枝叶制成细而长的竿子，通常用来搭脚手架或撑船。', example:''},
    {type:'WORDS', name:'铺板', desc:'铺(pu4)板：搭床铺用的木板。', example:'他和妈住在里间，我在外间睡～。'},
    {type:'WORDS', name:'牛腩', desc:'牛腩(na3n)：〈方〉牛肚子上和近肋骨处的松软肌肉，也指用它做成的菜肴。', example:''},
    {type:'WORDS', name:'病殁', desc:'病殁(mo4)：病死。', example:''},
    {type:'WORDS', name:'大伯子', desc:'大伯(ba3i)子(zi)：称丈夫的哥哥。', example:''},
    {type:'WORDS', name:'揣手儿', desc:'揣(chua1i)手儿：两手重叠交错地伸进袖子里。', example:''},
    {type:'WORDS', name:'挣揣', desc:'挣(zhe4ng)揣(chua4i)：①努力争取②挣(zhe1ng)扎(zha2)③振作。', example:''},
    {type:'WORDS', name:'监生', desc:'监(jia4n)生：明清两代称在国子监读书或取得进国子监读书资格的人。国子监是明清两代的最高学府，照规定必须贡生或荫生才有资格入监读书，所谓荫生即依靠父祖的官位而取得入监的官僚子弟，此种荫生亦称荫监。监生也可以用钱捐到的，这种监生，通称例监，亦称捐监。', example:''},
    {type:'WORDS', name:'褫夺', desc:'褫(chi3)夺：依法剥夺。', example:''},
    {type:'WORDS', name:'彳亍', desc:'彳(chi4)亍(chu4)：慢步行走；形容小步慢走或时走时停。', example:''},
    {type:'WORDS', name:'鹰隼', desc:'鹰隼(su3n)：或指幼鹰，实际上是两种猛禽，泛指凶猛的鸟，用来比喻凶猛或勇猛。常用于比喻天性凶狠而令人畏惧的人或勇猛的人 。中国歼14战斗机即以"鹰隼"命名。隼为国家二级保护动物，不可掠杀。', example:''},
    {type:'WORDS', name:'铁锹', desc:'铁锹(qia1o)：一种农具，用于耕地，铲土。长柄多有木制，头是铁的，还可军用。', example:''},
    {type:'WORDS', name:'荨麻疹', desc:'荨(xu2n)麻疹：一种过敏性皮疹，俗称风疹疙疸。是由于皮肤、黏膜小血管扩张及渗透性增加而出现的一种局限性水肿反应，通常在2～24小时内消退，但反复发生新的皮疹。病程迁延数日至数月。临床上较为常见。另注意单独前两字读音：荨(qia2n)麻。', example:''},
    {type:'WORDS', name:'骰子', desc:'骰(to2u)子(zi)：亦作“色(sha3i)子(zi)”。用象牙、骨头或塑料做的小四方块;每面刻有点数;从一到六;常用一对做各种游戏或赌博;玩法是先摇动骰子，然后抛掷使两个骰子都随意停止在一平面上。', example:''},
    {type:'WORDS', name:'烘焙', desc:'烘焙(be4i)：又称为烘烤、焙烤，是指在物料燃点之下通过干热的方式使物料脱水变干变硬的过程。', example:''},
    {type:'WORDS', name:'堡子', desc:'堡(bu3)子(zi)：有围墙的村镇，又多用于地名。', example:''},
    {type:'WORDS', name:'绥靖', desc:'绥(sui2)靖：绥，本义是借以登车的绳索，引申为安定、安抚。靖，安定之意。即以安抚（绥）的手段使局势安定（靖），又称为姑息主义。“慰抚”之意。中华民国政府在中国大陆时期曾设立过多个“绥靖公署”，意图维护地区局势。绥靖有保持地方平静；安抚平定；过去反动政府不顾事理道义，使人民屈从于暴力和强权之下以求安定的意思。现多用于形容政策性的手段，是一种通过在某些可能导致战争的事务上作出让步来讨好某个咄咄逼人的竞争对手的外交政策。一般用于贬义。', example:''},
    {type:'WORDS', name:'疖子', desc:'疖(jie1)子(zi)：皮肤病，由葡萄球菌或链状菌侵入毛囊内引起。症状是局部出现充血硬块，化脓，红肿，疼痛。', example:''},
    {type:'WORDS', name:'低徊', desc:'低徊(hui2)：1.徘徊，流连。2.回味；留恋地回顾。3.形容萦绕回荡。', example:''},
    {type:'WORDS', name:'貉子', desc:'貉(ha2o)子(zi)：貉子又名狸、土狗、土獾、毛狗、貉子，是哺乳纲、食肉目，犬科，貉属半冬眠，貉子皮的外形象狐，但比狐小，体肥短粗，四肢短而细，尾毛蓬松，背毛呈黑棕或棕黄色，针毛尖部黑色，背中央掺尽可能较多的黑毛梢，它具有针毛长、底绒丰厚、细柔灵活耐磨，光泽好，皮板结实，保温力很强的特点。', example:''},
    {type:'WORDS', name:'捩转', desc:'捩(lie4)转(zhua3n)：扭转;转动。', example:''},
    {type:'WORDS', name:'摞起', desc:'摞(luo4)起：摞 luò 〈动〉 通常指整齐地堆积或堆起 [stack up]。如:把砖摞起来 摆或放置成堆或好像成堆 [pile up]。如:把碗摞在一起 摞 luò 〈量〉 常为有序的叠堆 [stack]。如:一摞书 堆在一起的或逐个叠放的大量东西 [pile]。如:一摞砖。', example:''},
    {type:'WORDS', name:'窥伺', desc:'窥(kui1)伺(si4)：1.暗中观察或监视。2. 觊觎。3、指暗中观望，等待时机（含贬义）。', example:'他～着，看谁将是今晚的受害者。'},
    {type:'WORDS', name:'相差', desc:'相差(cha4)：彼此差别。', example:''},
    {type:'WORDS', name:'负箧', desc:'负箧(qie4)：谓携书游学。箧，书箱。背着小箱子，比喻为学习而奔波。', example:''},
    {type:'WORDS', name:'脚癣', desc:'脚癣(xua3n)：一种皮肤病。病原体是一种霉菌，多发生在脚趾之间。症状是起水泡，奇痒，抓破后流黄水，严重时溃烂。通称脚气。', example:''},
    {type:'WORDS', name:'绦虫', desc:'绦(ta1o)虫：一种蠕虫(多节绦虫亚纲)，是寄生性动物，成虫生活在脊椎动物包括人的消化道中，幼虫在脊椎动物和无脊椎动物的许多种类中都有。', example:''},
    {type:'WORDS', name:'挑剔', desc:'挑剔(ti1)：在细节上过分苛刻指摘。', example:''},
    {type:'WORDS', name:'皴裂', desc:'皴(cu1n)裂：皮肤因寒冷而冻裂。', example:''},
    {type:'WORDS', name:'着落', desc:'着(zhuo2)落：1. 事情有归宿、有结果。2. 依托；靠头；指靠。', example:'老头子只担心小女儿将来没～。'},
    {type:'WORDS', name:'疆埸', desc:'疆埸(yi4)：1.边界,边防。2.田边，田界。3.疆土，领土。4.指战场。', example:''},
    {type:'WORDS', name:'堙塞', desc:'堙(yi1n)塞(se4)：堵塞。', example:''},
    {type:'WORDS', name:'氛围', desc:'氛(fe2n)围：指围绕或归属于一特定根源的有特色的高度个体化的气氛。', example:'人们在欢乐的～中迎来了新的一年。'},
    {type:'WORDS', name:'侘傺', desc:'侘(cha4)傺(chi4)：形容失意的样子。', example:''},
    {type:'WORDS', name:'日晷', desc:'日晷(gui3)：本义是指太阳的影子。现代的“日晷”指的是人类古代利用日影测得时刻的一种计时仪器，又称“日规”。其原理就是利用太阳的投影方向来测定并划分时刻，通常由晷针（表）和晷面（带刻度的表座）组成。利用日晷计时的方法是人类在天文计时领域的重大发明，这项发明被人类沿用达几千年之久。', example:''},
    {type:'WORDS', name:'弄堂', desc:'弄(lo4ng)堂：即小巷，是上海和江浙地区特有的民居形式，它是由连排的 老房子（包括石库门）所构成的，并与石库门建筑有着密切的关系。', example:''},
    {type:'WORDS', name:'饥馑', desc:'饥馑(ji3n)：也就是灾荒；指因为粮食歉收等引起的食物严重缺乏的状况。', example:''},
    {type:'WORDS', name:'遴选', desc:'遴(li2n)选：慎重地选拔;审重选择。', example:''},
    {type:'WORDS', name:'拘泥', desc:'拘泥(ni4)：指固执成见而不知变通；拘束；不自然。', example:'要在看得活络，无所～，则无不通耳。'},
    {type:'WORDS', name:'抨击', desc:'抨(pe1ng)击：用文字或言语来严厉驳斥、攻击。', example:''},
    {type:'WORDS', name:'稽首', desc:'稽(qi3)首：指古代汉族跪拜礼，为九拜中最隆重的一种。常为臣子拜见君父时所用。跪下并拱手至地，头也至地。稽首，稽是“停留，拖延”的意思，稽首的意思就是头触碰在地上且停留一会儿。', example:''},
    {type:'WORDS', name:'黥刑', desc:'黥(qi2ng)刑：又名墨刑，黵刑，刺字，上古的五刑之一，是中国古代封建社会中使用时间最长的一种肉刑。', example:''},
    {type:'WORDS', name:'洗涮', desc:'洗涮(shua4n)：指洗涤衣物。解释为用水摇动或放在水里摆动洗清。', example:''},
    {type:'WORDS', name:'倭寇', desc:'倭(wo1)寇：指十四至十六世纪侵扰劫掠中国和朝鲜沿海地区的日本海盗，除沿海劫掠以外主要从事中日走私贸易。抗日战争期间，中国人亦用倭寇指称日本侵略者。', example:''},
    {type:'WORDS', name:'迤逦', desc:'迤(yi3)逦(li3)：1、曲折连绵。2、亦作“迤里”或“迆逦”，形容唱歌声和鸟鸣声的悠扬圆转曲折连绵。', example:'队伍沿着山道～而行。'},
    {type:'WORDS', name:'锁钥', desc:'锁钥(yue4)：1.锁钥，开锁的器件，比喻成事的关键所在。2.喻指在军事上相当重要的地方。', example:''},
    {type:'WORDS', name:'豇豆', desc:'豇(jia1ng)豆：俗称角豆、姜豆、带豆、挂豆角。茎蔓生,叶子由三个菱形小叶合成,花淡紫色。果实为圆筒形长荚果,种子呈肾脏形。', example:''},
    {type:'WORDS', name:'蒙骗', desc:'蒙(me1ng)骗：欺骗或哄骗。词语本身含有靠蒙来骗人这个意思。也就是说骗人有很多种方法，而蒙骗只是其中之一，骗人者通过模糊、扰乱受骗者等手段以达到自己骗人的目的。', example:''},
    {type:'WORDS', name:'坍圮', desc:'坍(ta1n)圮(pi3)：坍圮崖岸或建筑物或堆起的东西倒塌，从基部崩坏。', example:''},
    {type:'WORDS', name:'葳蕤', desc:'葳(we1i)蕤(rui2)：1.草木茂盛，枝叶下垂的样子。2.委顿;委靡不振。', example:''},
    {type:'WORDS', name:'贫窭', desc:'贫窭(ju4)：1.亦作“贫寠”。贫乏，贫穷。2.指贫穷的人。', example:''},
    {type:'WORDS', name:'株连', desc:'株连：指一人有罪而牵连他人。株，本指露出地面的树根，根与根之间牵连甚多。', example:''},
    {type:'WORDS', name:'赘述', desc:'赘(zhui4)述：1.说些不必要的细节。2.重复累赘的叙述。', example:''},
    {type:'WORDS', name:'荣膺', desc:'荣膺(yi1ng)：荣膺，动词，光荣地获得。膺：承受，承当。', example:''},
    {type:'WORDS', name:'端倪', desc:'端倪(ni2)：事情的头绪迹象。', example:''},
    {type:'WORDS', name:'媾和', desc:'媾(go4u)和：交战国缔结和约,结束战争状态。也指一国之内交战团体达成和平协议，结束战争。有时泛指交战国为结束战争状态，恢复和平关系所进行的整个活动过程，包括交战国一方提出媾和建议、进行谈判和缔结停战协议、和约等。若参战同盟国之一单独同敌国媾和称单独媾和。有些同盟条约规定不得单独媾和。', example:''},
    {type:'WORDS', name:'蕴藉', desc:'蕴藉(jie4)：就是藏在其内，隐藏而不外露的意思，多形容君子气质。也指言语，文字，神情等含蓄而不显露。文学话语蕴藉的方法是灵活的，多变的，不断发展的，有赖于我们在实践中不断探索、不断总结。', example:''},
    {type:'WORDS', name:'亟待', desc:'亟(ji2)待：迫切等待 急切需要。', example:''},
    {type:'WORDS', name:'伏法', desc:'伏法：指罪犯被执行死刑。依法被处死刑。', example:''},
    {type:'WORDS', name:'省察', desc:'省(xi3ng)察：反省检查自己。', example:''},
    {type:'WORDS', name:'讨嫌', desc:'讨嫌：指惹人厌烦嫌恶；讨厌。', example:'～不已。'},
    {type:'WORDS', name:'唏嘘', desc:'唏嘘：本意是哭泣后不由自主地急促呼吸；现在通常指：无奈，自然，感慨，叹息的意思。也做欷歔。', example:''},
    {type:'WORDS', name:'剀切', desc:'剀(ka3i)切(qie4)：1、跟事理完全相合。2、切实。', example:''},
    {type:'WORDS', name:'巷道', desc:'巷(ha4ng)道：1.略与地面平行、用于采矿探矿的坑道。2.窄街道。', example:''},
    {type:'WORDS', name:'押解', desc:'押解(jie4)：押送犯人或俘虏，旧指监督运送财物。', example:''},
    {type:'WORDS', name:'恚恨', desc:'恚(hui4)恨：愤恨、怨恨。', example:''},
    {type:'WORDS', name:'褊狭', desc:'褊(bia3n)狭：褊：狭小，狭隘。狭：窄，不宽阔。气量狭窄;土地狭小。', example:''},
    {type:'WORDS', name:'胸脯', desc:'胸脯(pu2)：指胸部；胸膛。', example:''},
    {type:'WORDS', name:'市侩', desc:'市侩(kua4i)：旧指买卖的中间人，现泛指唯利是图的人。', example:''},
    {type:'WORDS', name:'炕席', desc:'炕(ka4ng)席：我国北方农村以及部分城市普遍睡火炕。火炕的是由土坯或砖块搭成，炕面多由沙土抹成。为了清洁，炕面上要铺上一层席子“炕席”。', example:''},
    {type:'WORDS', name:'下载', desc:'下载(za4i)：把信息从互联网或其他电子计算机上输入到某台电子计算机上（跟‘上载’相对）。', example:''},
    {type:'WORDS', name:'惨怛', desc:'惨怛(da2)：“惨”同“憯”。悲痛；忧伤。', example:'民有菜色，惨怛于心。'},
    {type:'WORDS', name:'哭丧', desc:'哭丧(sa1ng)：1.有丧事时，吊祭的人和守灵的人大声号哭。2.悲哀的样子。', example:''},
    {type:'WORDS', name:'乖角儿', desc:'乖角(jue2)儿：聪明机灵的人。', example:''},
    {type:'WORDS', name:'揪心', desc:'揪(jiu1)心：1、焦虑；2、极言令人悲痛；极度痛苦的。', example:''},
    {type:'WORDS', name:'甲壳', desc:'甲壳(qia4o)：虾、蟹等动物的外壳，由石灰质及色素等构成，质地坚硬。', example:''},
    {type:'WORDS', name:'屎壳郎', desc:'屎壳(ke)郎(la4ng)：又名粪金龟；学名蜣螂（Geotrupidae），也有很多人叫它屎虼（gè）螂、屎比房、推丸、裹粪牛、滚粪牛、滚粪郎等，属鞘翅目金龟子科粪金龟亚科。世界上约有 2300 种蜣螂，分布在南极洲以外的任何一块大陆。蜣螂能利用月光偏振现象进行定位，以帮助取食。有一定的趋光性。钻进牛粪里的虫类，可以将粪便滚动成球状，推行向前。主要以动物粪便为食，有“自然界清道夫”的称号，又名“莫多昇”。', example:''},
    {type:'WORDS', name:'折耗', desc:'折(she2)耗：货物在运送、保存过程中，数量上的损失。', example:''},
    {type:'WORDS', name:'走俏', desc:'走俏：指畅销或受欢迎。', example:''},
    {type:'WORDS', name:'娇嗔', desc:'娇嗔(che2n)：一般用来形容女孩子伪装生气怪男孩子，但是时间不会超过两分钟就会转怒为喜，用以区分真正的嗔怒。', example:''},
    {type:'WORDS', name:'瞋目', desc:'瞋(che2n)目：瞪大眼睛表示愤怒。', example:'～怒视'}
];